# Generated by Django 6.1 on 2026-08-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram chat ID"
            ),
        ),
        migrations.CreateModel(
            name="TelegramConnectionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Хеш кода"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Действует до")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_connection_code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код подключения Telegram",
                "verbose_name_plural": "Коды подключения Telegram",
            },
        ),
    ]
